[project]
name = "anki"
version = "0.1.0"
description = "A Python package for creating and managing Anki flashcards."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "genanki>=0.13.1",
    "pandas>=2.2.3",
]
